before:
  hooks:
    - go mod download

builds:
  - id: protoc-gen-go-grpc-service-config
    binary: protoc-gen-go-grpc-service-config
    main: ./protoc-gen-go-grpc-service-config/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
  prerelease: auto
